### ISSUE TITLE
generateChangelog task hangs

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/gradle-github-changelog#29]
Reported by @yooksi.

> the task execution hangs seemingly indefinitely - currently looking at 5 minutes execution time and counting up.
> 
> Any idea what might be causing this issue now?

Gradle version: 6.8.2
Plugin version: 1.3.0

**Comment by joffrey-bion** [comment]
Are you providing `githubToken` (making logged in requests), or are you using it non-logged in?
I know there is some rate-limiting on GitHub side for non-logged in requests.

Also, do you have lots of issues and tags in your repo?

**Comment by yooksi** [comment]
The problem seems to have resolved itself after running the task a couple of more times.
The issue must have been caused by either my cache or something on Github side.

The task now executes correctly and within a few seconds time with and without providing the token.

**Comment by joffrey-bion** [comment]
Awesome that this is solved. I wonder what caused that.

Please don't hesitate to open other issues if you have any problems.
