### ISSUE TITLE
private repo support?

### ISSUE THREAD

**Issue by peterfigure** [joffrey-bion/gradle-github-changelog#40]
Hi - does this work with private repos? I'm just getting:

```
Could not find repository: https://api.github.com/repos/xxx/yyy
```

I do supply a Personal Access Token

**Comment by joffrey-bion** [comment]
Private repos should be supported. Are you trying to access a private repo from another user/organization?

**Comment by peterfigure** [comment]
nope, trying to run it in the gradle build for the repo (nefilim/test-build) i'm trying to access

```
changelog {
    githubUser = "nefilim"
    githubToken = findProperty("githubToken").toString()
    githubRepository = "test-build"

    title = "Change Log"
    showUnreleased = true
    unreleasedVersionTitle = "Unreleased"
    futureVersionTag = null
    sections = emptyList() // no custom sections by default, but default sections are prepended
    defaultIssueSectionTitle = "Closed issues:"
    defaultPrSectionTitle = "Merged pull requests:"
    includeLabels = emptyList()
    excludeLabels = listOf("duplicate", "invalid", "question", "wontfix")
    sinceTag = null
    skipTags = emptyList()
    skipTagsRegex = emptyList()
    releaseUrlTemplate = null // defaults to "https://github.com/$user/$repo/tree/%s"
    diffUrlTemplate = null // defaults to "https://github.com/$user/$repo/compare/%s...%s"
    releaseUrlTagTransform = { it }
    diffUrlTagTransform = { it }
//    customTagByIssueNumber = [:]
    useMilestoneAsTag = true
//    timezone = java.time.ZoneId.of("GMT")

    outputFile = file("${projectDir}/CHANGELOG.md")
}
```

**Comment by peterfigure** [comment]
looks like it was a token issue, I tried another token and it worked :|

**Comment by joffrey-bion** [comment]
Glad that it works eventually!

Was there any permission that the non-working token was missing? Or was it just invalid/expired?
If a particular permission is needed, I should update the documentation.

**Comment by peterfigure** [comment]
both tokens were unexpired, the one that did not work looked like this:

<img width="474" alt="Screen Shot 2021-12-30 at 13 44 23" src="https://user-images.githubusercontent.com/62901374/147786829-e0d351aa-9279-4a5d-88e8-378e671bb48a.png">

the one that worked looked like:

<img width="475" alt="Screen Shot 2021-12-30 at 13 44 40" src="https://user-images.githubusercontent.com/62901374/147786844-ff23dc5a-993f-4ce7-8042-b03e076839f2.png">

**Comment by joffrey-bion** [comment]
Thank you for the additional info, I will update the doc
